# This file was generated by GoReleaser. DO NOT EDIT.
cask "bosun" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "2f29145d014ab5fc3e2fc3251e6679f14535a771cd254546fb8c09d2687d6a1f"
      url "https://github.com/everydaydevopsio/bosun/releases/download/v#{version}/bosun_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "74b79ee9a523dc625602e9ceeaca10a0638855d6e60116c46d24fabbad2571a7"
      url "https://github.com/everydaydevopsio/bosun/releases/download/v#{version}/bosun_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5b27952cc78a3b58d0dd02641914b85a3d1bbf2b97b5b028b9a25ddff1d82b2b"
      url "https://github.com/everydaydevopsio/bosun/releases/download/v#{version}/bosun_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "226cf77a45a2b271d0fe8f168d23bf218f3ad4e5dce3304116884f4a013803ca"
      url "https://github.com/everydaydevopsio/bosun/releases/download/v#{version}/bosun_#{version}_linux_arm64.tar.gz"
    end
  end

  name "bosun"
  desc "Event-driven AI code-review controller for Kubernetes"
  homepage "https://github.com/everydaydevopsio/bosun"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bosun"

  # No zap stanza required

end
