# This file was generated by GoReleaser. DO NOT EDIT.
cask "bosun" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "be4d00ed21ba5b9706056a4e00db2610b16e21900b7efb5f71a58b87ae7b7102"
      url "https://github.com/everydaydevopsio/bosun/releases/download/v#{version}/bosun_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4cc9ece9974ed0fbb1f205ec4ec00f50e05b11c4c0ceaf348ab2d6fadfe931cc"
      url "https://github.com/everydaydevopsio/bosun/releases/download/v#{version}/bosun_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "82b20c98277163770210d2469bc70dcfd75d7c6e388912ffe711d0ccc3ce42d0"
      url "https://github.com/everydaydevopsio/bosun/releases/download/v#{version}/bosun_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "aa646a8816c32e1637eb69310cabd4c9133613c03ffcc0c5b2534c12367acae9"
      url "https://github.com/everydaydevopsio/bosun/releases/download/v#{version}/bosun_#{version}_linux_arm64.tar.gz"
    end
  end

  name "bosun"
  desc "Event-driven AI code-review controller for Kubernetes"
  homepage "https://github.com/everydaydevopsio/bosun"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bosun"

  # No zap stanza required

end
